### ISSUE TITLE
Don’t work on MacOS

### ISSUE THREAD

**Issue by Eleveres** [namuyan/srudp#5]
```
sock = SecureReliableSocket()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/srudp/__init__.py", line 201, in __init__
    super().connect(self_address)
OSError: [Errno 22] Invalid argument
```

**Comment by namuyan** [comment]
Thank you for report! but you don’t give me enough info to detect the problem.

What’s version of srudp do you use? This travis shows no error on Python3.8. What’s version of Python do you use? and is it from original dist and what’s your OS?

**Comment by Eleveres** [comment]
Hi, I'm running python3.8.2 on MacOS. I simply pip installed the package then tried running this code and it failed straight away.

**Comment by namuyan** [comment]
Thank you for reply!
In my environment, Windows and Ubuntu, I could not find your problem. We require detailed debugging at your env, MacOS. In particular, please pay attention to the object of getsockname().
It will need a few fix but I cannot determine what is because I don’t have Mac and time. However it is not expected that there will be any differences between envs.
